# Generated by Django 3.2.12 on 2022-03-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(unique=True, verbose_name='Уникальный ID')),
                ('phone', models.PositiveBigIntegerField(verbose_name='Телефон')),
                ('operator_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Код оператора')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тег')),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=30, null=True, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(unique=True, verbose_name='Уникальный ID')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Время запуска')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст сообщений')),
                ('date_stop', models.DateTimeField(auto_now_add=True, verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(unique=True, verbose_name='Уникальный ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания сообщения')),
                ('status', models.BooleanField(default=False, verbose_name='Статус отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail.client', verbose_name='Клиент')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail.mailinglist', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
