# Generated by Django 3.2.12 on 2022-03-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20220314_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='date_start',
            field=models.DateTimeField(verbose_name='Время запуска'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='date_stop',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
    ]
