# Generated by Django 3.2.12 on 2022-03-15 08:19

from django.db import migrations, models
from django_celery_beat.models import PeriodicTask, IntervalSchedule


def create_check_tasks_task(apps, schema_editor):
    """ Создает таску, для проверки не актуальный тасок
    """
    schedule, created = IntervalSchedule.objects.get_or_create(
        every=1,
        period=IntervalSchedule.MINUTES,
    )
    PeriodicTask.objects.create(
        interval=schedule,
        name="Check Tasks",
        task="mail.check_tasks_task",
        enabled=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_auto_20220315_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='operator_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код оператора'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тег'),
        ),
        migrations.RunPython(create_check_tasks_task),
    ]
